pipeline:
  lint:
    image: dart:3.0.7
    commands:
      - dart pub --verbose get --no-precompile
      - dart analyze --fatal-infos --fatal-warnings
  test:
    image: dart:3.0.7
    commands:
      - dart pub get
      - dart test
  notify:
    image: git.polynom.me/papatutuwawa/woodpecker-xmpp:0.1.1-arm64
    settings:
      xmpp_muc: moxxy-build@muc.moxxy.org
      xmpp_tls: 1
    secrets: [ xmpp_jid, xmpp_password, xmpp_server ]
    when:
      status:
        - success
        - failure
